version: '3.7'

services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    networks: 
      - mongodb-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass

  mongo-express:
    image: mongo-express
    ports:
      - '8081:8081'
    networks: 
      - mongodb-network
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongo
    restart: unless-stopped

networks:
  mongodb-network:
