version: '3.7'

services:
  mongo:
    image:mongo
    ports:
      - "27017:27017"
    networks: 
      - mongodb-network
    environment:
      -MONGO_INITDB_ROOT_USERNAME=rootuser
      -MONGO_INITDB_ROOT_PASSWORD=rootpass

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    networks: 
      - mongodb-network
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb

networks:
  default:
    name: mongodb-network
